### ISSUE TITLE
No such file or directory: 'completions\\mask.png'

### ISSUE THREAD

**Issue by roshan-raj** [moodoki/semantic_image_inpainting#10]
`E:\Engineering\7th SEM\Final Project 2\Referal Codes\Extension\semantic_image_inpainting>python src/inpaint.py --model_file graphs/dcgan-100.pb --maskType center --in_image testimages/face1.png --nIter 3 --outDir completions --blend

Iteration 0: 227.1767120361328
Iteration 1: 214.17889404296875
Iteration 2: 202.74424743652344
Traceback (most recent call last):
  File "src/inpaint.py", line 119, in <module>
    main()
  File "src/inpaint.py", line 113, in main
    scipy.misc.imsave(os.path.join(args.outDir, 'mask.png'), mask)
  File "C:\Users\Dell\Anaconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\Dell\Anaconda3\lib\site-packages\scipy\misc\pilutil.py", line 219, in imsave
    im.save(name)
  File "C:\Users\Dell\Anaconda3\lib\site-packages\PIL\Image.py", line 1927, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'completions\\mask.png'`

getting this error when i try to run the [extension](https://github.com/moodoki/semantic_image_inpainting/tree/extensions)

![image](https://user-images.githubusercontent.com/31264823/52530744-8e8f9c80-2d2f-11e9-8ca8-00f7c611a107.png)

**Comment by moodoki** [comment]
Please ensure that outDir exists, in your case, create the 'completions' directory.
